services:
  fs-server:
    container_name: python-fs
    image: deploy:fsserver
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /macos-deployment
    tty: true
    stdin_open: true
    restart: unless-stopped
  cron-service:
    container_name: cron-job
    image: deploy:cronner
    volumes:
      - type: bind
        source: ./
        target: /macos-deployment
    tty: true
    stdin_open: true
    restart: unless-stopped