accounts:
  help:
    full_name: "Help.Account" # display name
    user_name: "help.account" # dir/user name
    password: "@ssistMe"
    admin: "no"
  client:
    full_name: "DONOTUSE"
    user_name: "DONOTUSE"
    password: "Password1"
    admin: "yes"
packages: # key: package to be installed | value: array of strings that matches these words
  teamviewer:
    - "TeamViewer"
  office_2016:
    - "Microsoft Word"
  AbsoluteFullAgent:
    - "Absolute"
search_directories:
  - "/Applications" 
  - "/Library/Application Support" 
file_vault: true
firewall: true