accounts:
  default:
    user_name: defaultuser0
    password: PASSWORD
    ignore_admin: true
  client:
    password: PASSWORD
    change_password: true
packages:
  chrome:
    - Chrome
  zoom:
    - zoom.us
search_directories:
  - /Applications 
admin:
  user_name: ADMIN
  password: PASSWORD
server_ip: https://127.0.0.1:5000
filevault: true
firewall: true
always_cleanup: false