accounts:
  help:
    user_name: TEST.USERNAME
    password: PASSWORD
    ignore_admin: true
  client:
    password: PASSWORD
    change_password: true
packages:
  teamviewer:
    - TeamViewer
  office_2016:
    - Microsoft Word
search_directories:
  - /Applications 
  - /Library/Application Support 
admin:
  user_name: USERNAME
  password: PASSWORD
server_ip: https://127.0.0.1:5000
filevault: true
firewall: true
always_cleanup: true