accounts:
  default:
    username: defaultuser0
    password: "PASSWORD"
    ignore_admin: true
  client:
    password: "PASSWORD"
    change_password: true
packages:
  chrome:
    - Chrome
  zoom:
    - zoom.us
search_directories:
  - /Applications 
admin:
  username: ADMIN
  password: "PASSWORD"
server_host: "https://127.0.0.1:5000"
log_output: "/some/path/here"
filevault: true
firewall: true