FROM debian:bookworm-slim AS zip-updater

ARG USER=updater
ARG GROUP=${USER}
ARG TIMER=2H

ENV HOME=/home/${USER}
ENV TIMER=${TIMER}

RUN groupadd ${GROUP} && useradd ${USER} -g ${GROUP}
RUN mkdir ${HOME} && chown ${USER}:${GROUP} ${HOME}

RUN apt-get update \ 
    && apt-get install -y \
    curl procps

COPY scripts/zip_updater.sh ${HOME}
RUN chown -R ${USER}:${GROUP} ${HOME}
WORKDIR ${HOME}
USER ${USER}

CMD /bin/bash -c "./zip_updater.sh ${TIMER}"