FROM debian:bookworm-slim AS zip-updater

ARG USER=updater
ARG GROUP=${USER}
ENV HOME=/home/${USER}

RUN groupadd ${GROUP} && useradd ${USER} -g ${GROUP}
RUN mkdir ${HOME} && chown ${USER}:${GROUP} ${HOME}

RUN apt-get update \ 
    && apt-get install -y \
    curl procps

COPY scripts/zip_updater.sh ${HOME}
RUN chown -R ${USER}:${GROUP} ${HOME}
WORKDIR ${HOME}
USER ${USER}

CMD [ "bash", "zip_updater.sh" ]