name: docker-test

on:
  workflow_dispatch:
  push: 
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build and start Docker
        run: |
          docker compose build
          docker compose up -d
      - name: Check Docker status
        run: |
          sleep 2
          containers=$(docker compose ps | grep -E "deploy:*")
          if [[ -z "$val" ]]; then
            echo "Failed to start containers"
            exit 1
          fi
      - name: Clean up
        run: docker compose down -v