name: docker-test

on:
  workflow_dispatch:
  push: 
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build and start Docker
        run: |
          docker compose build
          docker compose up -d
          docker compose down -v