name: mac-deployment
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Pulls the latest data from the repository.
        run: cd /home/default/mac-deployment && git pull