name: macdeploy-tests

on:
  pull_request:
    paths-ignore:
      - "*.md"
    branches: 
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build and test Go
        run: |
          cd src/tests
          go build ./...
          go test ./...
